apiVersion: v1
kind: Namespace
metadata:
  name: pnp-ltim-shravan-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pnp-ltim-shravan-deployment
  namespace: pnp-ltim-shravan-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:8ccedd9377e6a4a4462ec0d4fdc266bed1998235

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pnp-ltim-shravan-label
  name: pnp-ltim-shravan-service
  namespace: pnp-ltim-shravan-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---